# Generated by Django 5.2.14 on 2026-06-02 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined device asset name', max_length=255)),
                ('device_type', models.CharField(choices=[('CPE', 'Customer Premises Equipment'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('AP', 'Access Point'), ('FIREWALL', 'Firewall'), ('ONT', 'Optical Network Terminal')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='Hostname or IPv4/IPv6 Address')),
                ('location', models.CharField(help_text='Physical location or site placement', max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded')], default='OFFLINE', max_length=20)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_reported_at', 'name'],
                'indexes': [models.Index(fields=['current_status'], name='monitoring__current_57a103_idx'), models.Index(fields=['last_reported_at'], name='monitoring__last_re_6d9f05_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional diagnostics text', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='monitoring.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='monitoring__device__45fbdd_idx')],
            },
        ),
    ]
